version: '3.8'

services:
  backend:
    build: ./Backend
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend
      args:
        NEXT_PUBLIC_BACKEND_URL: "${NEXT_PUBLIC_BACKEND_URL}"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
    container_name: nextjs_frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - backend
